### PR TITLE
RateLimit

### PR DESCRIPTION
**Pull request by ttvfimin**
So, there is a chance that a rate limited response is actually a code. So what I added basically just checks the ratelimited code until it is either valid or invalid. Also removed a bunch of random new lines. Edit: I know its not a lot but there is a chance a code could be missed.

### CODE REVIEW

**Comment by kieronia** [comment]
Alright – thanks sm!

From Kieronia.
penus#0001 On Discord
Buy Cheap From http://kieronia.com/ 

From: Ben
Sent: 23 September 2020 20:37
To: kieronia/nitrogen
Cc: Subscribed
Subject: [kieronia/nitrogen] RateLimit (#2)

So, there is a chance that a rate limited response is actually a code. So what I added basically just checks the ratelimited code until it is either valid or invalid. Also removed a bunch of random new lines.

You can view, comment on, or merge this pull request online at:
  https://github.com/kieronia/nitrogen/pull/2
Commit Summary
• RateLimit
File Changes
• M nitrogen and oxygen.py (16) 
Patch Links:
• https://github.com/kieronia/nitrogen/pull/2.patch
• https://github.com/kieronia/nitrogen/pull/2.diff

**Comment by kieronia** [comment]
alright - working on proxy support now so ratelimits should be no more!

**Comment by ttvfimin** [comment]
Awesome! Can’t wait to see where this gets to in the futureOn 9/23/20 at 8:55 PM, Kieronia wrote:
                
            
            
                
                    From: "Kieronia" <notifications@github.com>Date: September 23, 2020To: "kieronia/nitrogen" <nitrogen@noreply.github.com>Cc: "Ben" <ben.voisey2@gmail.com>,"Author" <author@noreply.github.com>Subject: Re: [kieronia/nitrogen] RateLimit (#2)
                
                
alright - working on proxy support now so ratelimits should be no more!

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kieronia/nitrogen/pull/2#issuecomment-697938493",
"url": "https://github.com/kieronia/nitrogen/pull/2#issuecomment-697938493",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by harvey298** [comment]
Could we remove the if for switches?

**Comment by ttvfimin** [comment]
I tried out making the if statement one line, i haven’t tested it so please tell me if it works. also if that isn’t what you mean please tell me ahaOn 9/23/20 at 9:08 PM, harvey298 wrote:
                
            
            
                
                    From: "harvey298" <notifications@github.com>Date: September 23, 2020To: "kieronia/nitrogen" <nitrogen@noreply.github.com>Cc: "Author" <author@noreply.github.com>,"Ben" <ben.voisey2@gmail.com>Subject: Re: [kieronia/nitrogen] RateLimit (#2)
                
                
Could we remove the if for switches?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kieronia/nitrogen/pull/2#issuecomment-697944724",
"url": "https://github.com/kieronia/nitrogen/pull/2#issuecomment-697944724",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by harvey298** [comment]
Not rlly what I meant
JAVASCRIPT Example of a switch statement:

Switch (var) {
    Case "abc":
       Code
       Break;
    Case "def":
       Code
       Break;
    Default:
       Code
       Break;

^^^^ that's what I mean

**Comment by ttvfimin** [comment]
hmm, to be fair python isn’t my strongest language, so i wouldn’t know how to do that aha.Sent using the mobile mail appOn 9/23/20 at 9:14 PM, harvey298 wrote:
                
            
            
                
                    From: "harvey298" <notifications@github.com>Date: September 23, 2020To: "kieronia/nitrogen" <nitrogen@noreply.github.com>Cc: "Ben" <ben.voisey2@gmail.com>,"Author" <author@noreply.github.com>Subject: Re: [kieronia/nitrogen] RateLimit (#2)
                
                
Not rlly what I meant
JAVASCRIPT Example of a switch statement:
Switch (var) {
Case "abc":
Code
Break;
Case "def":
Code
Break;
Default:
Code
Break;
^^^^ that's what I mean

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kieronia/nitrogen/pull/2#issuecomment-697947956",
"url": "https://github.com/kieronia/nitrogen/pull/2#issuecomment-697947956",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by harvey298** [comment]
Switch statements r better then if statements it also makes it look clean

**Comment by ttvfimin** [comment]
i’ll try and do some research into it. thanks!Sent using the mobile mail appOn 9/23/20 at 9:18 PM, harvey298 wrote:
                
            
            
                
                    From: "harvey298" <notifications@github.com>Date: September 23, 2020To: "kieronia/nitrogen" <nitrogen@noreply.github.com>Cc: "Author" <author@noreply.github.com>,"Ben" <ben.voisey2@gmail.com>Subject: Re: [kieronia/nitrogen] RateLimit (#2)
                
                
Switch statements r better then if statements it also makes it look clean

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kieronia/nitrogen/pull/2#issuecomment-697949852",
"url": "https://github.com/kieronia/nitrogen/pull/2#issuecomment-697949852",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ttvfimin** [comment]
Hey! I did some research and to be honest, I don't think a switch statement is necessary. It's only checking one thing, and a switch statement would most likely over complicate things. Thanks for the suggestion though.On 23/09/2020 at 21:18, harvey298 wrote:
                
            
            
                
                    From: "harvey298" <notifications@github.com>Date: 23 September 2020To: "kieronia/nitrogen" <nitrogen@noreply.github.com>Cc: "Author" <author@noreply.github.com>,"Ben" <ben.voisey2@gmail.com>Subject: Re: [kieronia/nitrogen] RateLimit (#2)
                
                
Switch statements r better then if statements it also makes it look clean

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kieronia/nitrogen/pull/2#issuecomment-697949852",
"url": "https://github.com/kieronia/nitrogen/pull/2#issuecomment-697949852",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by harvey298** [comment]
fairs lmao

**Comment by harvey298** [comment]
@kieronia @ttvfimin I added the proxy thing using @kieronia IPLoggerSpammer code and it still gets rate limited but not as often, I'll make a pull request with the file, or you can check my fork.

**Comment by kieronia** [comment]
Alright I'll check it out tonight

**Pull request closed without merging**
